# Generated by Django 4.0.1 on 2022-01-18 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinedrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dine_name', models.CharField(max_length=100)),
                ('seaters', models.IntegerField()),
                ('air', models.IntegerField()),
                ('dine_type', models.CharField(choices=[('dine', 'Dine'), ('drink', 'Drink')], max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('dine_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('seaters', models.IntegerField()),
                ('air', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('event_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sparecreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spa_name', models.CharField(max_length=100)),
                ('spa_type', models.CharField(choices=[('spa', 'Spa'), ('recreation', 'Recreation')], max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('spa_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
